name: chatwoot_flutter_webview
description: A WebView wrapper for chatwoot.com chat widget
version: 0.0.1
repository: https://github.com/apexlabs-ai/chatwoot-flutter-webview
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webviewx: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter